version: "3"
services:
  db:
    image: postgres:9.6-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: backend
      POSTGRES_PASSWORD: password
  rails:
    build: backend
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3010 -b '0.0.0.0'"
    volumes:
      - ./backend:/backend
      - bundler-cache:/bundler
    ports:
      - "3010:3010"
    depends_on:
      - db
    environment:
      BACKEND_DATABASE_USER: backend
      BACKEND_DATABASE_PASSWORD: password
      BUNDLE_PATH: /bundler/vendor
  react:
    build: frontend
    command: yarn run start
    stdin_open: true
    volumes:
      - ./frontend:/frontend
    ports:
      - "3000:3000"
volumes:
  postgres-data:
  bundler-cache: